"""Add completed column to missions

Revision ID: 00588f722616
Revises: 
Create Date: 2024-11-08 12:01:47.398394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00588f722616'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missions', sa.Column('completed', sa.Boolean(), nullable=True))
    op.drop_column('missions', 'complete')
    op.add_column('targets', sa.Column('completed', sa.Boolean(), nullable=True))
    op.drop_column('targets', 'complete')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('targets', sa.Column('complete', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('targets', 'completed')
    op.add_column('missions', sa.Column('complete', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('missions', 'completed')
    # ### end Alembic commands ###
